# Generated by Django 4.2 on 2023-04-07 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LittleLemonApp', '0002_alter_booking_guestsnumber_alter_menu_inventory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu',
            name='inventory',
        ),
    ]
