# Generated by Django 4.2 on 2023-04-07 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LittleLemonApp', '0003_remove_menu_inventory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='bookingdate',
            field=models.DateTimeField(),
        ),
    ]
